name: Deploy Backend to PythonAnywhere

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r backend/requirements.txt

    - name: Pull latest code from GitHub
      run: git pull origin master

    - name: Deploy to PythonAnywhere
      env:
        PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        PYTHONANYWHERE_API_KEY: ${{ secrets.PYTHONANYWHERE_API_KEY }}
      run: |
        curl -X POST -u $PYTHONANYWHERE_USERNAME:$PYTHONANYWHERE_API_KEY https://www.pythonanywhere.com/api/v0/user/$PYTHONANYWHERE_USERNAME/webapps/Gogroupbuy/reload/
