name: Deploy Backend to PythonAnywhere

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r backend/requirements.txt

    - name: Execute cd on PythonAnywhere
      run: |
        curl -X POST \
            -H 'Authorization: Token ${{ secrets.PYTHONANYWHERE_API_KEY }}' \
            -d 'input=-e "cd /home/wangpython/Gogroupbuy\n"' \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/consoles/33326347/send_input/

    - name: Pull latest code on PythonAnywhere
      run: |
        curl -X POST \
            -H 'Authorization: Token ${{ secrets.PYTHONANYWHERE_API_KEY }}' \
            -d 'input=-e "git pull\n"' \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/consoles/33326347/send_input/


    - name: Reload webapp
      uses: jensvog/pythonanywhere-webapp-reload-action@v1
      with:
        host: 'www.pythonanywhere.com'
        username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        api-token: ${{ secrets.PYTHONANYWHERE_API_KEY }}
        domain-name: ${{ secrets.PYTHONANYWHERE_DOMAIN_NAME }}
